### ISSUE TITLE
GameBoard MapSizeの固定値の除去と描画の不具合修正

### ISSUE THREAD

**Issue by tomoino** [c-app-dev-waseda-group-f/waseda-c-application-development-2020-spring-group-work#26]
newGameBoardでmapSizeが引数のものを使うようにする。
mapSizeと実際に描画されるマスの数が食い違っていたので修正する

**Comment by yangminshun** [comment]
#12 と重なる部分があると思いますが。

**Comment by tomoino** [comment]
そうなんですけど、描画にバグがあって作業時に困りそうだと思ったので、これだけ別にして優先的に直すことにしました。
